
[build]
  command = "npm run build"
  publish = "dist"

# Redirections principales
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301              # Redirection permanente (SEO-friendly)

# Réécriture d'URL pour des chemins dynamiques (ex: /blog/123 → /articles/123)
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200              # Réécriture sans changement d'URL

# Cette redirection permet au fichier robots.txt d'être trouvé à la racine
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Cette redirection permet au sitemap.xml d'être trouvé à la racine
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Redirection spécifique pour la page blog - modification de l'ordre et priorité
# Cette règle doit être placée AVANT la règle générique "/*"
[[redirects]]
  from = "/blog"
  to = "/index.html"
  status = 200
  force = true              # Force la redirection

# Gestion des erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200              # Pour que les routes React fonctionnent correctement

# Sécurité et en-têtes (optionnel)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; img-src 'self' https: data:; font-src 'self' https: data:;"
